### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by TheLaughingManSAC** [pratham-darooka/stock-analysis-crew#1]
Hi, would it be possible to update this? 

As there have been many updates since you have made this project and the dependencies are driving me crazy at the moment, as I am not sure how I need to do this ;-;

Or at least can you show the versions of each dependecy because I have no idea

**Comment by pratham-darooka** [comment]
@TheLaughingManSAC of course! didn't know this would be seen by other people so created it like a personal project.

will do it over the next week, busy with other projects this weekend

**Comment by pratham-darooka** [comment]
@TheLaughingManSAC you might want to check [this](https://github.com/crewAIInc/crewAI-examples/blob/main/stock_analysis/README.md). Probably what you're looking for.

They have it updated with SEC API for reliable information. As for versions, I can give you the `requirement.txt` with versions next week.
